timecraft/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import WatchCategory, Watch, Order, watch_category_association, orderdetails
from datetime import datetime
from .forms import CheckoutForm
from . import db

bp = Blueprint('main', __name__)

@bp.route('/')
def index():
    featured = Watch.query.filter(Watch.featured == True).all()
    return render_template('index.html', featured = featured)

# Category pages
@bp.route('/<string:category_name>')
def watch_categories(category_name):
    watches = Watch.query.join(WatchCategory.watches).filter(WatchCategory.name == category_name).all()
    category = WatchCategory.query.filter(WatchCategory.name == category_name).first()
    return render_template('watchcategories.html', watches = watches, category = category)

# Search functionality
@bp.route('/search', methods=['POST'])
def search():
    search_query = request.form.get('search_query')
    watches = search_watches(search_query)
    return render_template('search.html', watches = watches)

def search_watches(query):
    return Watch.query.filter(Watch.name.ilike(f"%{query}%")).all()

# filter functionality
@bp.route('/<string:category_name>/filtered', methods=['POST'])
def filter(category_name):
    selected_brands = request.form.getlist('brand_filter')
    category_watches = Watch.query.join(WatchCategory.watches).filter(WatchCategory.name == category_name).all()
    category = WatchCategory.query.filter(WatchCategory.name == category_name).first()
    watches = [watch for watch in category_watches if watch.brand in selected_brands]
    return render_template('watchcategories.html', watches = watches, category = category)

# Product details pages
@bp.route('/<int:watch_id>')
def details(watch_id):
    watch = Watch.query.get(watch_id)
    return render_template('details.html', watch = watch)

# Referred to as "Cart" to the user
@bp.route('/order', methods=['POST','GET'])
def order():
    watch_id = request.values.get('watch_id')

    # retrieve order if there is one
    if 'order_id' in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', address='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except Exception as e:
            print(f'Failed at creating a new order: {e}')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    
    if order is not None:
        for watch in order.watches:
            totalprice = totalprice + watch.price*watch.quantity
    
    # are we adding an item?
    if watch_id is not None and order is not None:
        watch = Watch.query.get(watch_id)
        if watch not in order.watches:
            try:
                order.watches.append(watch)
                db.session.commit()
            except Exception as e:
                print(f"Error adding item to cart: {str(e)}")
                db.session.rollback()  # Rollback the session to avoid leaving the database in an inconsistent state
                flash('There was an issue adding the item to your cart. Please try again.')
            return redirect(url_for('main.order'))
        else:
            try:
                watch.quantity += 1
                db.session.commit()
            except Exception as e:
                print(f"Error adding item to cart: {str(e)}")
                db.session.rollback()  # Rollback the session to avoid leaving the database in an inconsistent state
                flash('There was an issue adding the item to your cart. Please try again.')
            return redirect(url_for('main.order'))
    
    return render_template('order.html', order = order, totalprice = totalprice)


# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        watch_to_delete = Watch.query.get(id)
        try:
            watch_to_delete.quantity = 1
            order.watches.remove(watch_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))


# Scrap basket
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        order = Order.query.get(session['order_id'])
        for watch in order.watches:
            watch.quantity = 1
        db.session.commit()
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.index'))


@bp.route('/checkout', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            order.address = form.address.data
            totalcost = 0
            for watch in order.watches:
                totalcost = totalcost + watch.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Your order is complete. Thank you for choosing Timecraft.')
                return redirect(url_for('main.index'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)

timecraft/templates/checkout.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block main %}
<section>
    <div class="checkout-container">
        <div class="row">
            <div class="col-12">
                <h1 id="checkout-title">Checkout</h1>
                <p>
                    Please provide your details below so that we can complete your
                    order.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{wtf.quick_form(form)}}
            </div>
        </div>
    </div>
</section>
{% endblock %}

timecraft/templates/details.html
{% extends 'base.html' %}

{% block main %}
<div class="container product-details">

    <img src="{{url_for('static', filename='img/'+watch.image)}}" alt="{{watch.name}}">

    <div class="product">
        <h2>{{watch.name}}</h2>
        <p>${{watch.price}}</p>
        <p>Quantity: </p>
        <div>
            <div class="input-group">
                <div class="input-group-prepend">
                    <button type="button" class="input-group-text">-</button>
                </div>
                <input type="text" class="form-control text-center" value="1">
                <div class="input-group-append">
                    <button type="button" class="input-group-text">+</button>
                </div>
            </div>
        </div>

        <div class="buy-or-add details-add-to-cart">
            <form class="card-link" action="{{ url_for('main.order') }}">
                <input type="hidden" id="watch_id" name="watch_id" value="{{ watch.id }}">
                <input class="btn btn-primary" id="product-add-to-cart" type="submit" value="Add to Cart">
            </form>
        </div>
    </div>
</div>
<div class="information container">
    <div>
        <h3>Description</h3>
        <p>{{watch.description}}</p>
    </div>

    <div class="product-specification">
        <h3 class="specification-title">Product Specification</h3>
        <table class="table">
            <thead>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Collection</th>
                    <td>{{watch.collection}}</td>
                </tr>
                <tr>
                    <th scope="row">Style</th>
                    <td>{{watch.style}}</td>
                </tr>
                <tr>
                    <th scope="row">Material</th>
                    <td>{{watch.material}}</td>
                </tr>
                <tr>
                    <th scope="row">Band/Strap</th>
                    <td>{{watch.strap_type}}</td>
                </tr>
                <tr>
                    <th scope="row">Dial Colour</th>
                    <td>{{watch.dial_colour}}</td>
                </tr>
                <tr>
                    <th scope="row">Glass</th>
                    <td>{{watch.glass}}</td>
                </tr>
                <tr>
                    <th scope="row">Watch Movement</th>
                    <td>{{watch.movement_type}}</td>
                </tr>
                <tr>
                    <th scope="row">Water Resistance</th>
                    <td>{{watch.water_resistance}}</td>
                </tr>
            </tbody>
        </table>
    </div>

</div>
{% endblock %}

timecraft/templates/index.html
{% extends 'base.html' %}

{% block main %}
<!-- Hero -->
<div class="p-5 text-center bg-image rounded-3" style="
background-image: url('static/img/watch-banner3.jpg'); 
background-size: cover; 
height: 400px;
">
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="text-white hero">
                <h2 class="mb-3 hero-title">Expertly crafted, Timeless pieces</h2>
                <h4 class="mb-3">
                    Welcome to Timecraft, where precision meets elegance in the art of timekeeping. Established
                    with a passion for craftsmanship and an unwavering commitment to quality, Timecraft is your
                    destination for exquisite watches that transcend mere functionality to become timeless
                    expressions of style.</h4>
                <a class="btn btn-outline-light btn-lg contact mb-3" href="#!" role="button">Contact Us</a>
            </div>
        </div>
    </div>
</div>
<!-- Hero -->
<!-- Featured item cards -->
<h2 class="my-3 featured-title">Featured Watches</h2>
<div class="container featured  my-3">
    {% for watch in featured %}
    <div class="card">
        <img class="card-img-top" src="{{url_for('static', filename='img/'+watch.image)}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{watch.name}}</h5>
            <p class="card-text">{{"$%.2f"|format(watch.price)}}</p>
            <div class="buy-or-add">
                <a href="{{url_for('main.details', watch_id=watch.id)}}" class="btn btn-primary card-link">View
                    Details</a>
                <form class="card-link" action="{{ url_for('main.order') }}">
                    <input type="hidden" id="watch_id" name="watch_id" value="{{ watch.id }}">
                    <input class="btn btn-primary" type="submit" value="Add to Cart">
                </form>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
</div>
<!-- Featured item cards -->
{% endblock %}

timecraft/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>
    <div class="container order-container">
        <div class="cart-title row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Cart</h3>
        </div>
        <!-- each watch on seperate row -->
        {% for watch in order.watches %}
        <div class="row shadow-md my-row mb-3">
            <div class="col-sm-10 card">
                <h5 class="card-header">{{watch.name}}</h5>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <img class="img-thumbnail" src="{{url_for('static', filename=('img/' + watch.image))}}">
                        </div>
                        <div class="col-10">
                            <!-- Item Description -->
                            <p class="card-text">{{watch.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br><br>
            <!-- right column has price and delete button -->
            <div class="col-sm-2 price-section">
                <!-- delete item button -->
                <h5>Qty: {{watch.quantity}}</h5>
                <h5>{{ "$%.2f"|format(watch.price) }}</h5>
                <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                    <input type="hidden" id="id" name="id" value="{{watch.id}}">
                    <input type="submit" value="Delete" class="btn btn-primary mb-3">
                </form>
            </div>
        </div>
        {% endfor %}

        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Total Price = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>

            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}